default_language_version:
  python: python3.10

repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --preserve-quotes, --indent, "2"]

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0-alpha.4
  hooks:
  - id: prettier
    types_or: [markdown, json]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements

- repo: local
  hooks:
  - id: format
    name: format
    entry: hatch fmt -f
    language: system
    types: [python]
  - id: lint
    name: lint
    entry: hatch fmt -l
    language: system
    types: [python]
  - id: types
    name: types
    entry: hatch env run -e types check
    language: system
    types: [python]
